default: &default
  host: localhost
  port: 6379

development:
  <<: *default

test:
  <<: *default

lab:
  host: <%= ENV.fetch('REDIS_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('REDIS_PORT') { 6379 } %>

production:
  host: <%= ENV.fetch('REDIS_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('REDIS_PORT') { 6379 } %>